# Stub mypy para o shadow module `cython` (Cython 3.3 não embarca py.typed).
#
# Escopo: o vocabulário Pure Python Mode usado neste projeto
# (plans/cython-pure-python-mode.md). Não é um stub completo do Cython.
#
# Escalares C são aliases dos tipos Python correspondentes — é o comportamento
# do modo interpretado e mantém atribuições/checagens válidas no mypy strict.
#
# Limitação conhecida: subscrições de memoryview (`cython.double[::1]`) não são
# representáveis com aliases; os módulos-kernel que as usam desativam o código
# de erro [index] via [[tool.mypy.overrides]] no pyproject.toml.

import builtins
from collections.abc import Callable
from typing import Any, TypeAlias, TypeVar, overload

_F = TypeVar("_F", bound=Callable[..., Any])
_T = TypeVar("_T")

# True quando o módulo está compilado; False no interpretador.
compiled: bool

# --- Escalares C (modo interpretado: tipo Python correspondente) ---
int: TypeAlias = builtins.int
long: TypeAlias = builtins.int
uint: TypeAlias = builtins.int
ulong: TypeAlias = builtins.int
short: TypeAlias = builtins.int
Py_ssize_t: TypeAlias = builtins.int
size_t: TypeAlias = builtins.int
double: TypeAlias = builtins.float
float: TypeAlias = builtins.float
bint: TypeAlias = builtins.bool

# --- Decoradores de função/classe (identidade no interpretador) ---
def cfunc(__func: _F) -> _F: ...
def ccall(__func: _F) -> _F: ...
def inline(__func: _F) -> _F: ...
def compile(__func: _F) -> _F: ...
def nogil(__func: _F) -> _F: ...
def cclass(__cls: type[_T]) -> type[_T]: ...
def final(__obj: _T) -> _T: ...

# --- Compiler directives locais ---
def annotation_typing(val: builtins.bool) -> Callable[[_F], _F]: ...
def boundscheck(val: builtins.bool) -> Callable[[_F], _F]: ...
def wraparound(val: builtins.bool) -> Callable[[_F], _F]: ...
def cdivision(val: builtins.bool) -> Callable[[_F], _F]: ...
def initializedcheck(val: builtins.bool) -> Callable[[_F], _F]: ...
def nonecheck(val: builtins.bool) -> Callable[[_F], _F]: ...
def overflowcheck(val: builtins.bool) -> Callable[[_F], _F]: ...
def exceptval(val: object, *, check: builtins.bool = ...) -> Callable[[_F], _F]: ...
def locals(**arg_types: object) -> Callable[[_F], _F]: ...
def infer_types(val: builtins.bool) -> Callable[[_F], _F]: ...

# --- Declarações e casts ---
@overload
def declare(**kwargs: type) -> None: ...
@overload
def declare(t: type[_T], value: _T) -> _T: ...
def cast(t: type[_T], value: object) -> _T: ...
def sizeof(obj: object) -> builtins.int: ...
def typeof(obj: object) -> str: ...

# namespace cimports (só válido compilado; mantido como Any no stub)
cimports: Any
